### ISSUE TITLE
bugs.webkit.org is currently feeding SEO AI spam mills

### ISSUE THREAD

**Issue by josephrocca** [WebKit/Documentation#107]
(I had no idea where to report this, so out of desperation I'm posting here. Can someone please forward this on to the relevant team member?)

Please add the `rel="nofollow"` attribute to all `<a>` tags in comments on `bugs.webkit.org`. Spammers are using it as part of an automated SEO spam pipeline. Here's an example:

* https://bugs.webkit.org/show_bug.cgi?id=201483

> The "IndexedDB: Connection to Indexed Database server lost" error can be frustrating, but it's not insurmountable. Before diving into the details, I’d like to recommend an interesting read on the psychology behind online games, which you can find here: hxxps // easyreadernews [dot] com / the-game-psychology-behind-australian-online-pokies-real-money Now, let's get into the topic at hand. By understanding the potential causes and taking proactive steps, both users and developers can minimize the impact of this issue.

(I've purposely 'broken' the link in this quote - the comment has an actual `<a>` tag.)

The `bugs.webkit.org` domain would likely have very high "authority", so this is a very "valuable" target for malicious actors.

**Comment by gsnedders** [comment]
Perhaps ironically, the correct place would be bugs.webkit.org. Filed this as https://bugs.webkit.org/show_bug.cgi?id=283017.

**Comment by aproskuryakov** [comment]
We should probably add it, but in prior discussions (circa 2019), we didn't expect any kind of actual benefit.
