### ISSUE TITLE
safe-merge-queue undocumented

### ISSUE THREAD

**Issue by gsnedders** [WebKit/Documentation#108]
Trying to understand what the behaviour of `merge-queue` v. `safe-merge-queue` v. `unsafe-merge-queue` is, I turned to are documentation.

However, https://docs.webkit.org/Getting%20Started/ContributingCode.html#merge-queue doesn't even mention `safe-merge-queue.

`merge-queue` could also be better documented; it currently says:

> Merge-Queue will validate that a pull request builds and run layout tests before landing the change.

But as far as I'm aware we only test this on a specific set of platforms and configurations.

**Comment by briannafan** [comment]
My attempt at better documentation:

> **Merge Queues**
> 
> To land a pull request, add the safe-merge-queue, merge-queue, or unsafe-merge-queue label to your pull request. These labels will put your pull request into Safe-Merge-Queue, Merge-Queue, or Unsafe-Merge-Queue, which will commit your pull request to the WebKit repository.
> 
> Each queue runs a style-check and inserts reviewer information into the commit message and modified change logs. They check that a pull request has been reviewed by checking the commit message before landing the change.
> 
> Safe-Merge-Queue checks the status of pull requests with the label every 15 minutes. Once all EWS tests pass, the pull request is automatically landed. If a test fails, the pull request is labelled with merging-blocked.
> 
> Merge-Queue will validate that a pull request builds on macOS and run WK2 layout tests before landing the change.
> 
> Unsafe-Merge-Queue does not perform any additional validation and should only be used for changes that have minimal impact (e.g. setting test expectations, adding to contributors.json) or changes that need to be landed quickly (e.g. build fix or revert).
>

**Comment by briannafan** [comment]
My attempt at better documentation:

> **Merge Queues**
> 
> To land a pull request, add the safe-merge-queue, merge-queue, or unsafe-merge-queue label to your pull request. These labels will put your pull request into Safe-Merge-Queue, Merge-Queue, or Unsafe-Merge-Queue, respectively, which will commit your pull request to the WebKit repository.
> 
> Each queue runs a style-check and inserts reviewer information into the commit message and modified change logs. They check that a pull request has been reviewed by checking the commit message before landing the change.
> 
> Safe-Merge-Queue checks the status of pull requests with the label every 15 minutes. Once all EWS tests pass, the pull request is automatically landed. If a test fails, the pull request is labelled with merging-blocked.
> 
> Merge-Queue validates that a pull request builds on macOS and runs WK2 layout tests before landing the change.
> 
> Unsafe-Merge-Queue does not perform any additional validation and should only be used for changes that have minimal impact (e.g. setting test expectations, adding to contributors.json) or changes that need to be landed quickly (e.g. build fix or revert).
>

**Comment by fujii** [comment]
ChangeLog has gone. We can remove "change logs".
