### ISSUE TITLE
Update doc regarding CMake headers

### ISSUE THREAD

**Issue by vitorroriz** [WebKit/Documentation#18]
I've started a [PR to the introduction document in WebKit repo](https://github.com/WebKit/WebKit/pull/7553). Once that lands we should update https://github.com/WebKit/Documentation/blob/main/docs/Deep%20Dive/Build/AddingNewFile.md

**Comment by stwrt** [comment]
Thanks for opening the issue. This should be addressed in #20.

**Comment by stwrt** [comment]
Merged the Cmake headers documentation. Closing out this issue.
