### ISSUE TITLE
blockquote is unreadable in dark mode

### ISSUE THREAD

**Issue by fujii** [WebKit/Documentation#47]
https://docs.webkit.org/Build%20%26%20Debug/Tests/#testharnessjs-tests

![Screenshot 2023-05-10 at 21 34 59](https://github.com/WebKit/Documentation/assets/36109/d5898780-2226-4e19-9074-fd4df19f8679)

**Comment by stwrt** [comment]
This should be fixed in https://github.com/WebKit/Documentation/pull/42
Wanted @jdatapple to take a look at that PR before I merge it.

There are a few other minor UI issues at the moment that I have noticed too.

Thanks for reporting this.

**Comment by stwrt** [comment]
I did actually have a PR for this here though that addressed it

https://github.com/WebKit/Documentation/pull/37

**Comment by stwrt** [comment]
These should be much more readable in the latest commit.

I completely re-did how we did the theming based on feedback from Martin.

Feel free to re-open if you see any other issues with the blockquote.

<img width="726" alt="dark" src="https://github.com/WebKit/Documentation/assets/1958441/1dbaa8b1-6d3d-4ddb-89e7-f4f1b9401e81">
<img width="727" alt="light" src="https://github.com/WebKit/Documentation/assets/1958441/289b83b6-298d-4582-9020-45d5604d2133">
