### ISSUE TITLE
[WebKit WWDC23 Blog post] [JPEG XL] Lossless JPEG Transcode saves ~20%, not 60%

### ISSUE THREAD

**Issue by antermin** [WebKit/Documentation#52]
First of all, sorry for opening the issue here. I understand that it may not be the most appropriate place, but I hope this can get maintainers' attention, so that the blog post can be updated to reflect correct information about JPEG XL.

In the [WebKit WWDC23 blog post](https://webkit.org/blog/14205/news-from-wwdc23-webkit-features-in-safari-17-beta/), it claimed that:

> And you can recompress existing JPEG files into JPEG XL without any loss of data while significantly reducing their size — up to 60%!

This is not the case - @jonsneyers (one of the core JPEG XL devs) has written the following in [this post](https://cloudinary.com/blog/the-case-for-jpeg-xl#lossless_jpeg_recompression):

> A unique feature of JPEG XL is that it is possible to recompress existing JPEG images (of which there are a lot out there!) to a JPEG XL file that is on average about 20% smaller, without introducing any loss. In fact, the bit-exact same JPEG file can be reconstructed from the JPEG XL file.

He also explained in the JPEG XL Discord ([link to message](https://discord.com/channels/794206087879852103/803574970180829194/1115618368309968937)):

> > And you can recompress existing JPEG files into JPEG XL without any loss of data while significantly reducing their size — up to 60%!
>
> That is also quite drastically wrong. Lossless recompression of JPEG will give you ~20% size reduction. The 60% size reduction is only true if you compare something like JPEG produced by a camera vs JXL produced from the same raw data at a quality similar to the JPEG quality.

Thank you very much in advance for looking into this.

**Comment by jensimmons** [comment]
Thanks for the question. To make the point more clearly, we changed the language to this:
 
> You can recompress existing JPEG files into JPEG XL without any loss of data, while reducing their size by an average of 20%. Or compress from the original image file to reduce the file up to 60% compared to JPEG!
