### ISSUE TITLE
make preview  error 64 -- Unknown option '--product'

### ISSUE THREAD

**Issue by zhiyuzhao** [WebKit/Documentation#7]
make preview

DOCC_HTML_DIR=ThirdParty/docc-render-artifact/dist swift package --disable-sandbox preview-documentation --product WebKit
error: Unknown option '--product'
Usage: swift package <options> <subcommand>
  See 'package --help' for more information.
make: *** [preview] Error 64

ENV
Version 13.0 (13A233)
macOS big Sur 11.4

**Comment by stwrt** [comment]
Thanks for the bug report. From a quick read over the Swift release notes it appears `--product` may have been introduced in Swift 5.6.

Can you try removing the `--product WebKit` from the Makefile and letting me know if it loads correctly for you.

**Comment by stwrt** [comment]
Closing out the issue. Please refer to the new install instructions in the ReadMe. If you have any further issues please feel free to open a new issue.
