### ISSUE TITLE
Unable to make docc target

### ISSUE THREAD

**Issue by brentfulgham** [WebKit/Documentation#8]
I ran the `make docc` command in the Documentation directory and got the following error:

```
xcodebuild: error: The workspace named "Documentation" does not contain a scheme named "WebKit". The "-list" option can be used to find the names of the schemes in the workspace.
make: *** [docc] Error 65

```

**Comment by stwrt** [comment]
The error appears to be the scheme is not defined yet on the first run of `xcodebuild`. After a second `make docc` it should work (and all subsequent runs). Opening the `Package.swift` file should also help resolve this. I need to find a proper solution for this.

This was difficult to reproduce on my machine as even deleting / re-downloading the repository would not reproduce. That is probably why I never caught this during development.
