### ISSUE TITLE
Windows Port S3 URL no longer visible?

### ISSUE THREAD

**Issue by DustinBrett** [WebKit/Documentation#85]
In regards to the [Windows Port](https://github.com/webkit/Documentation/blob/main/docs/Ports/WindowsPort.md#downloading-build-artifacts-from-buildbot) instructions, it's been pointed out to me that the step involving `transfer-to-s3` is no longer exists in the same way.

I went into a [recent build (15606)](https://build.webkit.org/#/builders/731/builds/15606) and I see now that the step is called `upload-file-to-s3` and it doesn't contain an S3 URL. I have gone back and found that [Build 15405](https://build.webkit.org/#/builders/731/builds/15405) was the last one to use `transfer-to-s3`.

## 15606 (upload-file-to-s3)
![image](https://github.com/WebKit/Documentation/assets/16656318/493af44e-33e9-4eef-a653-992918f2a75b)

## 15405 (transfer-to-s3)
![image](https://github.com/WebKit/Documentation/assets/16656318/a4fd77a1-f920-4029-bc88-08a7bfc57040)

I am wondering what the new recommended way is to get WinCairo setup, or where the new URL can be found?

**Comment by JonWBedard** [comment]
cc @briannafan, I'm going to file a Bugzilla on this. You can probably get the URL from the triggered build, but this seems like an oversight in the buildbot UI rather than a deliberate change.

**Comment by JonWBedard** [comment]
Bugzilla is https://bugs.webkit.org/show_bug.cgi?id=271840

**Comment by briannafan** [comment]
<img width="1055" alt="Screenshot 2024-03-28 at 11 25 17 AM" src="https://github.com/WebKit/Documentation/assets/23439563/8cbf9816-cb70-4647-a67c-51987004cd2e">

@DustinBrett The link to download the archive is now in the compile-webkit step so you no longer need to look in the logs for a URL. Hope that helps!

**Comment by DustinBrett** [comment]
> <img alt="Screenshot 2024-03-28 at 11 25 17 AM" width="1055" src="https://private-user-images.githubusercontent.com/23439563/317838606-8cbf9816-cb70-4647-a67c-51987004cd2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTE2MDEsIm5iZiI6MTcxMTY1MTMwMSwicGF0aCI6Ii8yMzQzOTU2My8zMTc4Mzg2MDYtOGNiZjk4MTYtY2I3MC00NjQ3LWE2N2MtNTE5ODcwMDRjZDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE4NDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NGJmN2IwMmYwOTRiYTg2OWQ3Yzg5NzE1NGVkM2FjZWJlZmQ1OTFkZDQ3Yzc3YjVjMGM5MjNkYzFkNTE5OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pcyir4PkWosN7u1xcqaiVaKnjqD7KchApQgwFTMKlD0">
> @DustinBrett The link to download the archive is now in the compile-webkit step so you no longer need to look in the logs for a URL. Hope that helps!

Thank you very much, the link in `compile-webkit` is great!
